# Site Settings
title: Students for Palestine Heidelberg
email: sfp_heidelberg@protonmail.com
description: >
  Students in Heidelberg standing with Palestine, advocating for free speech and against the ongoing genocide ğŸ‡µğŸ‡¸ğŸ•Šï¸
baseurl: ''
url: 'http://localhost:4000'
github_username: sfp-heidelberg
instagram_username: sfp_heidelberg

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
